version: "3"

services:
  mysql:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=Qhyv8LYr76VHawVYdeHDwBzGmVDQbn
      - MYSQL_USER=Fm7ZKtSoYaBbXeZT5wGYAnZU4Uz979
      - MYSQL_PASSWORD=WvPpZGiA8edUP7Qb77Q535JfZa36do
      - MYSQL_DATABASE=contact_form
    ports:
      - 3306:3306
    volumes:
      - ./mysql/:/var/lib/mysql/:delegated

  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - 1025:1025
      - 8025:8025
